grpc:
  port: ":50051"

http:
  port: ":8000"

database :
  host: "postgres"
  port : "5432"
  user : "postgres"
  password : "postgres"
  database : "url_shortener"
  sslmode : "disable"
  driver : "pgx"