version: "3"

volumes:
  postgres_volume:


services:
  postgres:
    build: ./third_party/docker_files/postgres
    environment:
      POSTGRES_DB: "url_shortener"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - postgres_volume:/var/lib/postgresql/data

  app:
    build: .
    ports:
      - "50051:50051"
      - "8000:8000"
    depends_on:
      - postgres
    links:
      - postgres